// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://humopleuhdsllgyhxiye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bW9wbGV1aGRzbGxneWh4aXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODUwNTEsImV4cCI6MjA1OTE2MTA1MX0.BDpRG-e9O-FtjSgMgtAkryoreJ_3AQsrp7Rt2OzkyFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);